dist: trusty
sudo: true 
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - mkdir my_dir 
  - cd my_dir
  - git clone https://github.com/Santhosh-KS/spookfish
  - cd cpp/build 
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build --release . -- -j2 
  - cmake --build . --config Release -- -j2

