dist: trusty
sudo: true 
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - build-essential
      - checkinstall 
      - cmake 
      - pkg-config 
      - yasm
      - git 
      - gfortran
      - libtiff4-dev
      - libjpeg8-dev
      - libjasper-dev
      - libpng12-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libdc1394-22-dev
      - libxine2-dev
      - libv4l-dev
      - libgstreamer0.10-dev 
      - libgstreamer-plugins-base0.10-dev
      - qt5-default
      - libgtk2.0-dev
      - libtbb-dev
      - libatlas-base-dev
      - libfaac-dev
      - libmp3lame-dev 
      - libtheora-dev
      - libvorbis-dev 
      - libxvidcore-dev
      - libopencore-amrnb-dev 
      - libopencore-amrwb-dev
      - x264 
      - v4l-utils
      - libeigen3-dev

script:
  - mkdir -p /opt
  - cd /opt
  - git clone https://github.com/davisking/dlib.git dlib
  - git clone https://github.com/opencv/opencv.git
  - git clone https://github.com/opencv/opencv_contrib.git
  - git clone https://github.com/Tencent/rapidjson.git
  - cd opencv_contrib
  - git checkout 3.3.1
  - cd /opt/opencv
  - git checkout 3.3.1
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON  -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules  -D BUILD_EXAMPLES=OFF ..
  - make -j4
  - make install
  - sh -c 'echo "/usr/local/lib" >> /etc/ld.so.conf.d/opencv.conf'
  - ldconfig
  - source ~/.bashrc
  - cd /opt
  - mkdir my_dir 
  - cd my_dir
  - git clone https://github.com/Santhosh-KS/spookfish
  - cd spookfish/cpp/build 
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . --config Release -- -j2
